spring.application.name=Web Ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce_user
spring.datasource.password=passworduntukecommerce1234)(*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server Configuration
spring.profiles.active=development
server.port=3000
server.servlet.context-path=/api/v1

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# flyway config
spring.flyway.enabled=true

# JWT Configuration
app.jwtSecret=843681e40db8dea6be899b7a8640f245e8b6ddef9c7f6fa5c61c5a6f54a3f7b5
app.jwtExpirationTime=3d
